// food-app/src/components/cart/CartItem.tsx
import { Fragment } from "react";
import Topping from "./topping/Topping";
import classes from "./Cart.module.scss";

function CartItem(props: any) {
  const price = `$${props.price.toFixed(2)}`;

  const foodToppingData = props.topping.map((foodItem: any) => (
    <Topping
      key={foodItem.id}
      id={foodItem.id}
      name={foodItem.name}
      price={foodItem.price}
      parrentKey={props.id}
    />
  ));

  return (
    <Fragment>
      <div id={props.id} className={classes["cart-item"]}>
        <div className={classes["cart-item_image"]}>
          <img src={props.image} alt={props.image} />
        </div>
        <div className={classes["cart-item_price"]}>
          <h3>{props.name}</h3>
          {foodToppingData}
          <div className={classes.action}>
            <button
              className={`${classes.btn} ${classes["btn-minus"]}`}
              onClick={props.onRemove}
            >
              -
            </button>
            <span className={classes.amount}>
              x {props.amount}*{price}
            </span>
            <button
              className={`${classes.btn} ${classes["btn-plus"]}`}
              onClick={props.onAdd}
            >
              +
            </button>
          </div>
          <button
            className={`${classes.btn} ${classes["btn-trash"]} ${classes.trash}`}
            onClick={props.onDelete}
          >
            <img src="images/trash.png" alt="trash" />
          </button>
        </div>
      </div>
    </Fragment>
  );
}

export default CartItem;

// food-app/src/app/food-app/cart/cart-item/cart-item.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { ListService } from "src/app/shared/list.service";

@Component({
  selector: "app-cart-item",
  templateUrl: "./cart-item.component.html",
  styleUrls: ["./cart-item.component.scss"],
})
export class CartItemComponent implements OnInit {
  @Input() foodCart: any;
  constructor(private listService: ListService) {}

  ngOnInit() {}

  plusCartItem(item: any) {
    this.listService.addCartData(item);
  }

  minusCartItem(item: any) {
    this.foodCart = this.listService.minusCartData(item);
  }

  onChangeAmount(amount, parrentKey, childId) {
    this.listService.changeCartData(amount, parrentKey, childId);
  }

  onDeleteCartData(id: number) {
    this.foodCart = this.listService.deleteCartData(id);
  }
}

<ng-template ngFor let-item [ngForOf]="foodCart">
  <div [id]="item.id" class="cart-item">
    <div class="cart-item_image">
      <img src="assets/{{ item.image }}" [alt]="item.name" />
    </div>
    <div class="cart-item_price">
      <h3>{{ item.name }}</h3>
      <div *ngFor="let childItem of item.topping">
        <h4>{{ childItem.name }}</h4>
        <input
          type="number"
          min="1"
          max="10"
          (change)="onChangeAmount($event.target.value, item.id, childItem.id)"
          [(value)]="childItem.amount"
        />
        x {{ childItem.price | currency }}
      </div>
      <div class="action">
        <button class="btn btn-minus" (click)="minusCartItem(item)">-</button>
        <span class="amount">
          x {{ item.amount }}*{{ item.price | currency }}</span
        >
        <button class="btn btn-plus" (click)="plusCartItem(item)">+</button>
      </div>
      <button class="btn btn-trash trash" (click)="onDeleteCartData(item.id)">
        <img src="assets/images/trash.png" alt="trash" />
      </button>
    </div>
  </div>
</ng-template>
